# Site Settings
title: My Resume
url: 'evaschilken.github.io'
baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Eva Schilken
tagline: Web Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I’m an experienced Senior Web Developer from Berlin looking for a new challenge.
<br><br>
I have 6 years experience in developing multi-country enterprise e-commerce websites with the Salesforce Commerce Cloud. After working hard for almost 5 years I decided in 2017 to make the cut and travel the world starting in India. My travels changed my perspective of life and work in general and taught me lots of good life lessons.
<br><br>
In early 2018 I settled down in Melbourne, Australia to work remotely as a freelance software engineer. Working abroad from various co-working spaces and being my own boss really inspired me. After a year I decided to return to Berlin knowing that something in my life was still missing.
<br><br>
Since I’m personally very invested in the sustainable lifestyle I could no longer justify myself to work in fashion e-commerce which is not the most sustainable industry. I’m ready to take the next step on my journey which is finding solutions in contrary to creating problems.
<br><br>
I’m very eager to dive into new projects that have purpose and where I can use my programming skills for something good.'


#sidebar links
email: eva@schilken.de
phone: +49 176 4380 7666
website: eva.schilken.de #do not add http://
linkedin: eva-schilken
github: evaschilken
twitter: '@easyeve'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
