# Site Settings
title: My Resume
url: 'evaschilken.github.io'
baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Eva Schilken
tagline: Web Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I’m an experienced Senior Web Developer from Berlin looking for a new challenge.
<br><br>
I have 6 years experience in developing multi-country enterprise e-commerce websites with the Salesforce Commerce Cloud. After 5 years of non-stop, full-time work in 2017 I felt a calling to experience more of our planet. I said farewell to my position and began to travel the world, starting in India. 
<br><br>
My travels across the world gave me an understanding of the fragile state that our planet is currently in, and I could no longer justify working in fashion e-commerce, knowing that it is environmentally unsustainable. So after a year in Melbourne I decided to return to Berlin to align my job with my values.
<br><br>
I am ready and eager to take the next step on my journey, and use my programming skills for something good; something that has a positive impact on the planet.'

#sidebar links
email: eva@schilken.de
phone: +49 163 9712117
website: eva.schilken.de #do not add http://
linkedin: eva-schilken
github: evaschilken
twitter: '@easyeve'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
