# Site Settings
title: My Resume
url: 'evaschilken.github.io'
baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Eva Schilken
tagline: Web Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I’m an experienced Senior Web Developer from Berlin looking for a new challenge during my stay in Melbourne.
<br><br>
I have 5 years experience in developing multi-country enterprise e-commerce websites with the Salesforce Commerce Cloud. After working hard for the past years I decided to make the cut and travel the world starting in India. My travels changed my perspective of life and work in general and taught me lots of good life lessons.
<br><br>
I’m very eager to dive into new projects now and learn new languages. I’m especially interested to get my hands on some React. '

#sidebar links
email: eva@schilken.de
phone: +61 426 134 923
website: eva.schilken.de #do not add http://
#linkedin: alandoe
github: evaschilken
twitter: '@easyeve'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
